language: python
sudo: enabled
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- nightly
- pypy
- pypy3
env:
  global:
  - CODECOV_TOKEN="b5b63c88-6a8f-4858-aac1-d0da33bd5c9d"
  - FLASK_PLUGINKIT_TEST_REDISURL="redis://@localhost"
  matrix:
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10
  - FLASK_VERSION=0.11
  - FLASK_VERSION=0.12
  - FLASK_VERSION=1.0
  - FLASK_VERSION=1.1.0
matrix:
  exclude:
  - python: '3.5'
    env: FLASK_VERSION=0.9
  - python: '3.6'
    env: FLASK_VERSION=0.9
  - python: pypy3
    env: FLASK_VERSION=0.9
  - python: pypy3
    env: FLASK_VERSION=0.11
  allow_failures:
  - python: nightly
  - python: "3.7"
services:
- redis-server
install:
- pip install -U -r dev-requirements.txt
- pip install redis
- pip install Flask==$FLASK_VERSION
- make dev
script:
- coverage run setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  user: saintic
  password:
    secure: qIFYcJ/u2xOYVrMe/UKjfygKj9gTzvtFHIs5v3LGtkFMc7QJ6jEEsC3yWh8upAB5iddb2pI5wLcrYn4J13sxMd7I0na+sDHyq/CKrN3qJzdmD2U9FlHI8eLoOCPCEAfySyvO7hgWhk5oga4eJarEZBlq+5UGb6YfQnx7J32ViHEBEBWD6GFKAwAwtKOAYtRqlsRyJjz/41JnphXK7tpcUHZIO0s0XVC765CnXvHDlLPzol+ynEJz0/avTKJkUhC+I961QTSUgZC+J9QJcSepg+Bq6EssoRF5ldVKpRtrsjTNAEc535z/5JsvddNK7/+iay2X42YDBSvxYIOrFuqFLJK7AxxdGtHhiU5nwkYbDMERDVOmHCBbSMSqTOt9HMT486RGnizKGUUyk9Gsc+xZcYa+vSg4C9bCVdTBaJQ31Rv5NraMV7+APtL6iCcFufWyv5dHjKiyDNBKFtvpxDKC3Y+Hd3mOiS8+INNNMRoxZ7tbgYrQ2u3MkAAwLEyWJ2qgJI/Rx9jSTUVRcaT6csxwmSWNrvakUr3vZUR7EVA6nOcp7ShnCclEPTKgmqFZYqC3gA9KoO2MF/mSNYosrlCTPc23WEKqVobkqlLWVCR6dpw3k0JbPLB5rSIsHXz2dXdWDsHa45WhCiz6nfAsUpqGlk9NIty+NXuTrcQaE54HqAo=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    python: 2.7
    condition: "$FLASK_VERSION = 1.0"
    tags: true
    branch: master
