language: python
python:
  - "2.6"
  - "2.7"
sudo: enabled
install:
  - pip install setuptools twine wheel flask==0.10.1 unittest2
  - python setup.py build
  - python setup.py install
script:
  - python setup.py test
