language: python
python:
  - "2.6"
  - "2.7"
sudo: enabled
install:
  - pip install setuptools twine wheel flask==0.10.1
  - python setup.py build
  - python setup.py install
script:
  - python tests/test_web.py
  - python tests/test_installer.py