language: python
sudo: enabled
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
env:
  global:
  - CODECOV_TOKEN="a6a7750b-16dd-4694-a827-6940755771ab"
  matrix:
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10
  - FLASK_VERSION=0.12
  - FLASK_VERSION=1.0
  - FLASK_VERSION=1.1.0
matrix:
  exclude:
    - python: "3.5"
      env: FLASK_VERSION=0.9
    - python: "3.6"
      env: FLASK_VERSION=0.9
    - python: "3.7"
      env: FLASK_VERSION=0.9
    - python: "pypy3"
      env: FLASK_VERSION=0.9
install:
  - pip install -U -r dev-requirements.txt
  - pip install Flask==$FLASK_VERSION
  - make dev
script:
  - coverage run setup.py test
after_success:
  - codecov
