language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: enabled
install:
  - pip install -U setuptools twine wheel flask
  - make dev
script:
  - make test
  - nosetests --with-coverage
after_success:
  - codecov